### ISSUE TITLE
Uncaught ReferencError: browser is not defined

### ISSUE THREAD

**Issue by zaakirio** [raven0230/Remove-Youtube-Shorts#2]
I'm getting the following error running the extension on Chromium 107.0.5
![image](https://user-images.githubusercontent.com/90780598/212772613-f572ce79-3826-4ff1-af8f-fdd21a60b18a.png)

**Comment by raven0230** [comment]
Sorry for the late reply. This extension is only developed for Firefox, and there is no planning to support cross-browser.
