### ISSUE TITLE
[Bug] Youtube subscription feed can only load videos older than a month.

### ISSUE THREAD

**Issue by Reposave** [raven0230/Remove-Youtube-Shorts#5]
When this extension is enabled, the youtube subscription feed can only load videos that are **specifically** 4 weeks old, I submitted a report which was incorrect that said it can load videos older than 4 weeks old but it actually cannot do that. It loads only 4 week old videos. Sometimes it can load videos that are of a different age old but I'm not sure which age as I couldn't reproduce it again. I'm using Windows 11, Firefox browser Version 112.0.2

**Comment by SigmaTheDJ** [comment]
For me, my Subscription page does not load at all when this extension is enabled. I just get a spinning loading circle that never goes away.

If I disable the extension, the Subscriptions page works fine, but obviously the awful Shorts come back.

I'm using Windows 10 with Firefox 113.0.1.

EDIT - Disabling "Hide Shorts from Subscriptions page" in the context menu on YouTube, then restarting Firefox fixes this, but obviously the Shorts still show on the Subscription page.

**Comment by aaronpim** [comment]
I am having similar issues as well. The fix that Sigma stated above has returned my subscription page, but that has removed some of the functionality of the add-on.

**Comment by raven0230** [comment]
Sorry for any inconvenience caused. As I had used list view in subscription page for years, I forgot that there is grid view as well. 
I have just uploaded a new version, trying to fix problems in grid view.
May you guys update the extension and test if it works?

And if you guys are using list view, and still encounter this problem, please let me know.

**Comment by aaronpim** [comment]
> 

Thank you, this has fixed the issue completely (for me). I hope you have a great day.

**Comment by SigmaTheDJ** [comment]
It works fine for me too. Thanks very much for the fast fix!

**Comment by bambanah** [comment]
Can confirm latest update fixes subscription page for me. Thanks for the quick release!

**Comment by Reposave** [comment]
Thanks for fixing the issue raven :)
