### ISSUE TITLE
[Bug] Youtube Subscriptions page won't load

### ISSUE THREAD

**Issue by KSneijders** [raven0230/Remove-Youtube-Shorts#6]
Hi, first of all, thanks so much for this extension, it's great!

Since a day or two my subscriptions feed won't load when this add-on is enabled. 
I've disabled every other extension but "Remove Youtube Shorts" and it still won't load. 
Enabling everything except "Remove Youtube Shorts" (or enabling nothing) makes it work fine. 

I don't see anything obvious in the console/network tab, although I don't know exactly what to look for.

I'm on firefox if that helps. If you need any more info, let me know!

Add-on info:
- Version: 1.2
- Last Updated: 14 May 2023

<img src="https://github.com/raven0230/Remove-Youtube-Shorts/assets/32707500/fc873843-4904-4f39-94e0-7328977c1182" width="600">

<img src="https://github.com/raven0230/Remove-Youtube-Shorts/assets/32707500/a8294ba3-b947-4679-927e-425387434311" width="600">

**Comment by raven0230** [comment]
Sorry for any inconvenience caused. As I had used list view in subscription page for years, I forgot that there is grid view as well. 
I have just uploaded a new version, trying to fix problems in grid view.
May you update the extension and test if it works?

And if you are using list view, and still encounter this problem, please let me know.

**Comment by KSneijders** [comment]
@raven0230 Thanks for the quick update! You're correct in assuming I use the grid view, and it is now all working as expected!

I just had the complete opposite experience and completely forgot list view was thing😄 If I'd remembered I'd have checked to see if that worked but good to see you figured it out!
